use crate::{
    CC,
    geneds::{
        GenEd::{self, *},
        GenEdReq::*,
    },
    schedule::CourseCode,
};

pub fn geneds() -> Vec<GenEd> {
    vec![
        Core {
            name: "English Composition".to_string(),
            req: Courses {
                num: 1,
                courses: vec![CC!("ENGL", 1000), CC!("ENGL", 1010), CC!("HONR", 1030)],
            },
        },
        Core {
            name: "Intro to Theo".to_string(),
            req: Courses {
                num: 1,
                courses: vec![CC!("THEO", 1100)],
            },
        },
        Core {
            name: "Wellness for Life".to_string(),
            req: Courses {
                num: 1,
                courses: vec![CC!("EXSC", 1115), CC!("NURS", 3200)],
            },
        },
        Core {
            name: "Natural Philosophy".to_string(),
            req: Courses {
                num: 1,
                courses: vec![CC!("PHIL", 2100), CC!("PHIL", 2310)],
            },
        },
        Core {
            name: "Foreign Language".to_string(),
            req: SetOpts(vec![
                vec![CC!("SPAN", 1000), CC!("SPAN", 1020)],
                vec![CC!("GREK", 1000), CC!("GREK", 1020)],
                vec![CC!("ITAL", 1000), CC!("ITAL", 1020)],
                vec![CC!("LATN", 1000), CC!("LATN", 1020)],
                vec![CC!("FREN", 1000), CC!("FREN", 1020)],
                vec![CC!("THEO", 2010), CC!("THEO", 2020)],
                vec![CC!("ESLG", 2930)],
            ]),
        },
        Core {
            name: "Physical Fitness".to_string(),
            req: Courses {
                num: 1,
                courses: vec![
                    CC!("EXSC", 1100),
                    CC!("EXSC", 1101),
                    CC!("EXSC", 1105),
                    CC!("EXSC", 1106),
                    CC!("EXSC", 1107),
                    CC!("EXSC", 1108),
                    CC!("EXSC", 1109),
                    CC!("EXSC", 1111),
                    CC!("EXSC", 1114),
                    CC!("EXSC", 1116),
                    CC!("EXSC", 1117),
                    CC!("EXSC", 1126),
                    CC!("EXSC", 1128),
                    CC!("EXSC", 1129),
                    CC!("MILS", 1160),
                    CC!("MILS", 2160),
                    CC!("MILS", 3160),
                ],
            },
        },
        Foundation {
            name: "Faith".to_string(),
            req: Credits {
                num: 6,
                courses: vec![
                    CC!("ECON", 3260),
                    CC!("ENGL", 4130),
                    CC!("HIST", 3544),
                    CC!("THEO", 2000),
                    CC!("THEO", 2100),
                    CC!("THEO", 2144),
                    CC!("THEO", 2150),
                    CC!("THEO", 3100),
                    CC!("THEO", 3110),
                    CC!("THEO", 3144),
                    CC!("THEO", 3150),
                    CC!("THEO", 3160),
                    CC!("THEO", 3200),
                    CC!("THEO", 3220),
                    CC!("THEO", 3230),
                    CC!("THEO", 3240),
                    CC!("THEO", 3260),
                    CC!("THEO", 3280),
                    CC!("THEO", 3420),
                    CC!("THEO", 3430),
                    CC!("THEO", 3450),
                    CC!("THEO", 3620),
                    CC!("THEO", 3640),
                    CC!("THEO", 3660),
                    CC!("THEO", 3680),
                    CC!("THEO", 3690),
                    CC!("THEO", 3820),
                    CC!("THEO", 3840),
                    CC!("THEO", 3920),
                    CC!("THEO", 3940),
                    CC!("THEO", 3950),
                    CC!("THEO", 3960),
                    CC!("THEO", 4000),
                ],
            },
        },
        Foundation {
            name: "Aesthetic Experience".to_string(),
            req: Credits {
                num: 6,
                courses: vec![
                    CC!("ARCH", 2300),
                    CC!("ARCH", 2301),
                    CC!("ART", 1000),
                    CC!("ART", 1010),
                    CC!("ART", 1030),
                    CC!("ART", 2410),
                    CC!("ART", 2600),
                    CC!("ART", 2800),
                    CC!("DANC", 3800),
                    CC!("ENGL", 1020),
                    CC!("ENGL", 1500),
                    CC!("ENGL", 1550),
                    CC!("ENGL", 1575),
                    CC!("ENGL", 1600),
                    CC!("ENGL", 1650),
                    CC!("ENGL", 1700),
                    CC!("ENGL", 1750),
                    CC!("ENGL", 3010),
                    CC!("ENGL", 3020),
                    CC!("ENGL", 3030),
                    CC!("ENGL", 3040),
                    CC!("ENGL", 3060),
                    CC!("ENGL", 3110),
                    CC!("ENGL", 3120),
                    CC!("ENGL", 3140),
                    CC!("ENGL", 3150),
                    CC!("ENGL", 4010),
                    CC!("ENGL", 4020),
                    CC!("ENGL", 4050),
                    CC!("ENGL", 4060),
                    CC!("ENGL", 4110),
                    CC!("ENGL", 4130),
                    CC!("ENGL", 4140),
                    CC!("ENGL", 4200),
                    CC!("FIAR", 1100),
                    CC!("FREN", 3040),
                    CC!("FREN", 3620),
                    CC!("FREN", 3630),
                    CC!("FREN", 3640),
                    CC!("FREN", 3650),
                    CC!("FREN", 3700),
                    CC!("HIST", 3542),
                    CC!("HIST", 3660),
                    CC!("ITAL", 3000),
                    CC!("LATN", 3110),
                    CC!("LATN", 3120),
                    CC!("LATN", 4110),
                    CC!("LATN", 4120),
                    CC!("MCOM", 1030),
                    CC!("MCOM", 1610),
                    CC!("MCOM", 2600),
                    CC!("MCOM", 2610),
                    CC!("MCOM", 3600),
                    CC!("MCOM", 3610),
                    CC!("MUSC", 1100),
                    CC!("MUSC", 1101),
                    CC!("MUSC", 1102),
                    CC!("MUSC", 4100),
                    CC!("MUSC", 4110),
                    CC!("MUSC", 4120),
                    CC!("SOCI", 3330),
                    CC!("SPAN", 3040),
                    CC!("SPAN", 3650),
                    CC!("SPAN", 3660),
                    CC!("SPAN", 4700),
                    CC!("THEO", 2144),
                    CC!("THEO", 3133),
                    CC!("THTR", 1010),
                    CC!("THTR", 3800),
                ],
            },
        },
        Foundation {
            name: "Historical Inquiry".to_string(),
            req: Credits {
                num: 6,
                courses: vec![
                    CC!("ARCH", 2300),
                    CC!("ARCH", 2301),
                    CC!("ART", 3411),
                    CC!("ART", 3412),
                    CC!("ART", 3413),
                    CC!("ENGL", 1550),
                    CC!("ENGL", 1700),
                    CC!("ENGL", 1750),
                    CC!("FINC", 4940),
                    CC!("FREN", 3610),
                    CC!("HIST", 1100),
                    CC!("HIST", 1101),
                    CC!("HIST", 1300),
                    CC!("HIST", 1380),
                    CC!("HIST", 3100),
                    CC!("HIST", 3140),
                    CC!("HIST", 3141),
                    CC!("HIST", 3301),
                    CC!("HIST", 3380),
                    CC!("HIST", 3381),
                    CC!("HIST", 3383),
                    CC!("HIST", 3520),
                    CC!("HIST", 3521),
                    CC!("HIST", 3522),
                    CC!("HIST", 3540),
                    CC!("HIST", 3541),
                    CC!("HIST", 3542),
                    CC!("HIST", 3543),
                    CC!("HIST", 3660),
                    CC!("HIST", 3661),
                    CC!("HIST", 3680),
                    CC!("HIST", 3681),
                    CC!("HIST", 3682),
                    CC!("HIST", 3684),
                    CC!("HIST", 3685),
                    CC!("HIST", 3686),
                    CC!("HIST", 3687),
                    CC!("HIST", 3720),
                    CC!("ITAL", 3000),
                    CC!("MUSC", 1102),
                    CC!("MUSC", 4100),
                    CC!("MUSC", 4120),
                    CC!("POLS", 1100),
                    CC!("POLS", 1500),
                    CC!("POLS", 1800),
                    CC!("POLS", 3600),
                    CC!("POLS", 3750),
                    CC!("SPAN", 3710),
                    CC!("SPAN", 3720),
                    CC!("THEO", 3420),
                    CC!("THEO", 3430),
                    CC!("THEO", 3960),
                    CC!("THTR", 3810),
                    CC!("THTR", 3820),
                    CC!("THTR", 3830),
                ],
            },
        },
        Foundation {
            name: "Mathematical Reasoning".to_string(),
            req: Credits {
                num: 3,
                courses: vec![
                    CC!("BUSI", 2650),
                    CC!("MATH", 1020),
                    CC!("MATH", 1120),
                    CC!("MATH", 1220),
                    CC!("MATH", 1250),
                    CC!("MATH", 1300),
                    CC!("MATH", 1350),
                    CC!("MATH", 2550),
                    CC!("PSYC", 2010),
                ],
            },
        },
        Foundation {
            name: "Person and Community".to_string(),
            req: Credits {
                num: 3,
                courses: vec![
                    CC!("ARCH", 3400),
                    CC!("ART", 4311),
                    CC!("BUSI", 3710),
                    CC!("BUSI", 4550),
                    CC!("CRIM", 1000),
                    CC!("ECON", 1000),
                    CC!("ECON", 1010),
                    CC!("ECON", 2090),
                    CC!("ECON", 2100),
                    CC!("ECON", 3010),
                    CC!("ENGR", 3170),
                    CC!("MCOM", 1000),
                    CC!("NASC", 2300),
                    CC!("POLS", 1000),
                    CC!("POLS", 1500),
                    CC!("POLS", 1800),
                    CC!("POLS", 2010),
                    CC!("POLS", 3000),
                    CC!("POLS", 3250),
                    CC!("POLS", 3700),
                    CC!("POLS", 3750),
                    CC!("POLS", 3850),
                    CC!("POLS", 4010),
                    CC!("POLS", 4600),
                    CC!("PSYC", 1000),
                    CC!("SOCI", 1000),
                    CC!("SOCI", 2250),
                    CC!("SOCI", 2350),
                    CC!("SOCI", 3205),
                    CC!("SOCI", 3450),
                ],
            },
        },
        Foundation {
            name: "Philosophical Inquiry".to_string(),
            req: Credits {
                num: 6,
                courses: vec![
                    CC!("BUSI", 4550),
                    CC!("EDUC", 4451),
                    CC!("ENGL", 4110),
                    CC!("NURS", 4700),
                    CC!("PHIL", 2010),
                    CC!("PHIL", 2550),
                    CC!("PHIL", 3250),
                    CC!("PHIL", 3550),
                    CC!("PHIL", 3670),
                    CC!("PHIL", 3690),
                    CC!("PHIL", 3730),
                    CC!("PHIL", 3740),
                    CC!("PHIL", 3800),
                    CC!("PHIL", 3820),
                    CC!("PHIL", 4010),
                    CC!("PHIL", 4020),
                    CC!("PHIL", 4030),
                    CC!("PHIL", 4040),
                    CC!("PHIL", 4050),
                    CC!("PHIL", 4060),
                    CC!("PHIL", 4800),
                    CC!("PHIL", 4860),
                    CC!("POLS", 1100),
                    CC!("POLS", 3850),
                ],
            },
        },
        Foundation {
            name: "Natural World".to_string(),
            req: Credits {
                num: 7,
                courses: vec![
                    CC!("ASTR", 1300),
                    CC!("ASTR", 1400),
                    CC!("BIOL", 1050),
                    CC!("BIOL", 1105),
                    CC!("BIOL", 1107),
                    CC!("BIOL", 1121),
                    CC!("BIOL", 1122),
                    CC!("BIOL", 2243),
                    CC!("CHEM", 1010),
                    CC!("CHEM", 1011),
                    CC!("CHEM", 1200),
                    CC!("CHEM", 1201),
                    CC!("CHEM", 1210),
                    CC!("CHEM", 1211),
                    CC!("ENGR", 1001),
                    CC!("NASC", 1000),
                    CC!("NASC", 1100),
                    CC!("NASC", 1400),
                    CC!("NASC", 1600),
                    CC!("NASC", 2300),
                    CC!("NASC", 3100),
                    CC!("PHYS", 1100),
                    CC!("PHYS", 1200),
                    CC!("PHYS", 1300),
                    CC!("PHYS", 2000),
                    CC!("PHYS", 2001),
                    CC!("PHYS", 2100),
                    CC!("PHYS", 2101),
                    CC!("PHYS", 2110),
                    CC!("PHYS", 2111),
                    CC!("PSYC", 4050),
                ],
            },
        },
        SkillAndPerspective {
            name: "Global Perspective".to_string(),
            req: Courses {
                num: 1,
                courses: vec![
                    CC!("ART", 3411),
                    CC!("ECON", 4010),
                    CC!("ENGL", 1550),
                    CC!("ENGL", 1575),
                    CC!("FREN", 3500),
                    CC!("FREN", 3650),
                    CC!("GNST", 3000),
                    CC!("GNST", 3200),
                    CC!("HIST", 1100),
                    CC!("HIST", 1101),
                    CC!("HIST", 3140),
                    CC!("HIST", 3280),
                    CC!("HIST", 3541),
                    CC!("HIST", 3684),
                    CC!("HIST", 3686),
                    CC!("HIST", 3720),
                    CC!("MGMT", 3250),
                    CC!("MUSC", 1101),
                    CC!("MUSC", 4120),
                    CC!("NASC", 2300),
                    CC!("POLS", 2010),
                    CC!("POLS", 3000),
                    CC!("SOCI", 2350),
                    CC!("SOCI", 3305),
                    CC!("SPAN", 3500),
                    CC!("THEO", 2100),
                    CC!("THEO", 2150),
                    CC!("THEO", 3150),
                    CC!("THEO", 3820),
                ],
            },
        },
        SkillAndPerspective {
            name: "Oral Communication".to_string(),
            req: Courses {
                num: 1,
                courses: vec![
                    CC!("ARCH", 4116),
                    CC!("ART", 4900),
                    CC!("ASTR", 4200),
                    CC!("BIOL", 3305),
                    CC!("BUSI", 2230),
                    CC!("CENG", 4610),
                    CC!("CHEM", 4903),
                    CC!("CIVL", 4700),
                    CC!("CSCI", 4930),
                    CC!("EDUC", 4492),
                    CC!("EDUC", 4496),
                    CC!("EDUC", 4497),
                    CC!("EENG", 4600),
                    CC!("ENGL", 4910),
                    CC!("ESLG", 2930),
                    CC!("EXSC", 4457),
                    CC!("GNST", 1110),
                    CC!("GNST", 1800),
                    CC!("HIST", 4000),
                    CC!("MATH", 4930),
                    CC!("MCOM", 3310),
                    CC!("MENG", 4700),
                    CC!("MKTG", 3100),
                    CC!("MUSC", 2214),
                    CC!("NURS", 4200),
                    CC!("PHYS", 4910),
                    CC!("POLS", 4950),
                    CC!("PSYC", 4850),
                    CC!("SPCH", 1100),
                    CC!("THTR", 1150),
                ],
            },
        },
        SkillAndPerspective {
            name: "Scientific Method".to_string(),
            req: Courses {
                num: 1,
                courses: vec![
                    CC!("ASTR", 1300),
                    CC!("ASTR", 1400),
                    CC!("BIOL", 1050),
                    CC!("BIOL", 1105),
                    CC!("BIOL", 1107),
                    CC!("BIOL", 1121),
                    CC!("CHEM", 1010),
                    CC!("CHEM", 1200),
                    CC!("NASC", 1400),
                    CC!("NASC", 1600),
                    CC!("NASC", 3100),
                    CC!("PHYS", 1100),
                    CC!("PHYS", 1200),
                    CC!("PHYS", 2000),
                    CC!("PHYS", 2100),
                    CC!("PHYS", 2110),
                    CC!("POLS", 2500),
                    CC!("PSYC", 2010),
                    CC!("SOCI", 3155),
                    CC!("SOCI", 4175),
                ],
            },
        },
        SkillAndPerspective {
            name: "Visual Communication".to_string(),
            req: Courses {
                num: 1,
                courses: vec![
                    CC!("ART", 1000),
                    CC!("ART", 1010),
                    CC!("ART", 1030),
                    CC!("ART", 2410),
                    CC!("ART", 2800),
                    CC!("BIOL", 3305),
                    CC!("BUSI", 2230),
                    CC!("BUSI", 2650),
                    CC!("CENG", 4610),
                    CC!("CHEM", 4903),
                    CC!("CRIM", 3200),
                    CC!("CSCI", 4930),
                    CC!("EDUC", 2220),
                    CC!("EENG", 4600),
                    CC!("ENGL", 3150),
                    CC!("ENGR", 1500),
                    CC!("EXSC", 3380),
                    CC!("EXSC", 4457),
                    CC!("FREN", 3700),
                    CC!("HIST", 3385),
                    CC!("MATH", 4930),
                    CC!("MCOM", 1610),
                    CC!("MCOM", 2500),
                    CC!("MCOM", 2600),
                    CC!("MCOM", 2610),
                    CC!("MCOM", 3600),
                    CC!("MCOM", 3610),
                    CC!("MUSC", 3201),
                    CC!("NASC", 3100),
                    CC!("NURS", 3350),
                    CC!("PHYS", 4910),
                    CC!("PSYC", 4850),
                    CC!("SPAN", 3710),
                    CC!("SPAN", 3720),
                    CC!("THEO", 2144),
                    CC!("THTR", 1150),
                    CC!("THTR", 2150),
                    CC!("THTR", 3520),
                    CC!("THTR", 3560),
                    CC!("THTR", 3580),
                    CC!("THTR", 4150),
                ],
            },
        },
        SkillAndPerspective {
            name: "Western Perspective".to_string(),
            req: Courses {
                num: 1,
                courses: vec![
                    CC!("ARCH", 2300),
                    CC!("ART", 2410),
                    CC!("ART", 3412),
                    CC!("ART", 3413),
                    CC!("ENGL", 1020),
                    CC!("ENGL", 1500),
                    CC!("ENGL", 1550),
                    CC!("ENGL", 1575),
                    CC!("ENGL", 1600),
                    CC!("ENGL", 1650),
                    CC!("ENGL", 1700),
                    CC!("ENGL", 1750),
                    CC!("ENGL", 3010),
                    CC!("ENGL", 3020),
                    CC!("ENGL", 3040),
                    CC!("ENGL", 3120),
                    CC!("ENGL", 3140),
                    CC!("ENGL", 4110),
                    CC!("FREN", 3610),
                    CC!("FREN", 3620),
                    CC!("FREN", 3630),
                    CC!("FREN", 3640),
                    CC!("GNST", 3200),
                    CC!("HIST", 1100),
                    CC!("HIST", 1101),
                    CC!("HIST", 1300),
                    CC!("HIST", 1380),
                    CC!("HIST", 3100),
                    CC!("HIST", 3520),
                    CC!("HIST", 3521),
                    CC!("HIST", 3522),
                    CC!("HIST", 3540),
                    CC!("HIST", 3541),
                    CC!("HIST", 3542),
                    CC!("HIST", 3544),
                    CC!("HIST", 3660),
                    CC!("HIST", 3661),
                    CC!("HIST", 3681),
                    CC!("HIST", 3682),
                    CC!("HIST", 3684),
                    CC!("HIST", 3686),
                    CC!("ITAL", 3000),
                    CC!("PHIL", 2550),
                    CC!("PHIL", 3250),
                    CC!("PHIL", 4010),
                    CC!("PHIL", 4020),
                    CC!("PHIL", 4040),
                    CC!("PHIL", 4050),
                    CC!("PHIL", 4060),
                    CC!("POLS", 3010),
                    CC!("POLS", 4010),
                    CC!("SOCI", 3105),
                    CC!("SPAN", 3040),
                    CC!("THEO", 3420),
                    CC!("THEO", 3640),
                    CC!("THEO", 3820),
                ],
            },
        },
        SkillAndPerspective {
            name: "Written Communication".to_string(),
            req: Courses {
                num: 2,
                courses: vec![
                    CC!("ARCH", 2300),
                    CC!("ARCH", 2301),
                    CC!("ART", 3411),
                    CC!("ART", 3412),
                    CC!("ART", 3413),
                    CC!("ASTR", 4100),
                    CC!("ASTR", 4200),
                    CC!("ASTR", 4300),
                    CC!("BUSI", 2230),
                    CC!("BUSI", 4850),
                    CC!("CENG", 4600),
                    CC!("CHEM", 3511),
                    CC!("CIVL", 3010),
                    CC!("CIVL", 3020),
                    CC!("CRIM", 3100),
                    CC!("CRIM", 3300),
                    CC!("CSCI", 4930),
                    CC!("ECON", 3000),
                    CC!("EDUC", 4451),
                    CC!("EDUC", 4470),
                    CC!("EENG", 4600),
                    CC!("EENG", 4610),
                    CC!("ENGL", 1020),
                    CC!("ENGL", 1500),
                    CC!("ENGL", 1550),
                    CC!("ENGL", 1575),
                    CC!("ENGL", 1600),
                    CC!("ENGL", 1650),
                    CC!("ENGL", 1700),
                    CC!("ENGL", 1750),
                    CC!("ENGL", 3010),
                    CC!("ENGL", 3020),
                    CC!("ENGL", 3030),
                    CC!("ENGL", 3040),
                    CC!("ENGL", 3110),
                    CC!("ENGL", 3120),
                    CC!("ENGL", 3140),
                    CC!("ENGL", 3150),
                    CC!("ENGL", 3250),
                    CC!("ENGL", 3270),
                    CC!("ENGL", 4010),
                    CC!("ENGL", 4060),
                    CC!("ENGL", 4140),
                    CC!("ENGL", 4250),
                    CC!("ENGR", 3400),
                    CC!("ENGR", 3410),
                    CC!("ESLG", 2220),
                    CC!("EXSC", 4457),
                    CC!("FREN", 3510),
                    CC!("FREN", 3610),
                    CC!("FREN", 3700),
                    CC!("HIST", 2000),
                    CC!("HIST", 4000),
                    CC!("JOUR", 2620),
                    CC!("JOUR", 3300),
                    CC!("MATH", 4457),
                    CC!("MATH", 4930),
                    CC!("MGMT", 2250),
                    CC!("MUSC", 4100),
                    CC!("MUSC", 4110),
                    CC!("NURS", 4210),
                    CC!("PHIL", 4920),
                    CC!("POLS", 2500),
                    CC!("POLS", 2750),
                    CC!("PSYC", 2000),
                    CC!("PSYC", 2731),
                    CC!("SPAN", 3040),
                    CC!("SPAN", 3400),
                    CC!("THTR", 3810),
                    CC!("THTR", 3830),
                ],
            },
        },
    ]
}
